### ISSUE TITLE
Keybinding with multiple arguments

### ISSUE THREAD

**Issue by janschaible** [DHBW-FN/OxideWM#132]
In order to execute multiple commands for example create and move to, it might be usefull to accept multiple arguments for one keybinding.
Might be related to issue 128

the config would then look like the following
```
- keys: ["A", "l"]
    command: 
      name: Focus
      args: "right"
    command: 
      name: Focus
      args: "right"
```

## Acceptance Criteria
The user can execute multiple arguments with one keybinding
