### ISSUE TITLE
Config Parsers crashes when wrong datatype is specified in file

### ISSUE THREAD

**Issue by B1TC0R3** [DHBW-FN/OxideWM#133]
## Found in

- [test/ISSUE92-automated](https://github.com/DHBW-FN/OxideWM/tree/test/ISSUE92-automated)  
- 9a2046a2c58e3ea19c58748d21e0ae099ccb50ee

## Description

When setting a value in the file `config.yml` to the wrong datatype, the config parser in `src/config.rs` crashes.
This is an example of such invalid YAML code:

```yaml
cmds: 999
exec: [999,999]
exec_always: 999
border_with: "wide"
border_color: 999
border_focus_color: 0xFFFF00
gap: "small"
```

## Comments

Ideally, the parser should load the default values instead and log the faulty file with `error!();`
